clc
if (1)
    mex -I'src'  ...
        -I'src\os\arch\x86\inc' ... 
        -I'src\modem\inc' ...
        -I'src\app\inc' ...
        -I'src\os\inc' ...
        -I'src\modem'  ...
        src/test_modem_app.c ...
        src/modem/modem.c ...
        src/modem/modem_at.c ...
        src/modem/modem_cmd.c ...
        src/modem/modem_hal.c ...
        src/modem/modem_stats.c ...
        src/modem/modem_umi.c ...
        src/os/os.c ...
    
end

