#define MAKE_MEMBER_INDEX(n)    ((Umi_Member_t)(n))

/* Declaration of the structure umi_modem_sim_info_native_object_t. */
typedef struct
{
    egm_uint8_t model[32];
    egm_uint8_t SW_release[32];
    egm_uint8_t imei[32];
    egm_uint8_t ICCID[24];
    egm_uint8_t bnd_bitmap[24];
    egm_uint8_t rat;
    egm_int8_t status;
} umi_modem_sim_info_native_object_t;
#define UMI_STRUCT_MODEM_SIM_INFO_MODEL	MAKE_MEMBER_INDEX(0U)
#define UMI_STRUCT_MODEM_SIM_INFO_MODEL_SIZE	MAKE_MEMBER_SIZE(32U)
#define UMI_STRUCT_MODEM_SIM_INFO_SW_RELEASE	MAKE_MEMBER_INDEX(1U)
#define UMI_STRUCT_MODEM_SIM_INFO_SW_RELEASE_SIZE	MAKE_MEMBER_SIZE(32U)
#define UMI_STRUCT_MODEM_SIM_INFO_IMEI	MAKE_MEMBER_INDEX(2U)
#define UMI_STRUCT_MODEM_SIM_INFO_IMEI_SIZE	MAKE_MEMBER_SIZE(32U)
#define UMI_STRUCT_MODEM_SIM_INFO_ICCID	MAKE_MEMBER_INDEX(3U)
#define UMI_STRUCT_MODEM_SIM_INFO_ICCID_SIZE	MAKE_MEMBER_SIZE(24U)
#define UMI_STRUCT_MODEM_SIM_INFO_BND_BITMAP	MAKE_MEMBER_INDEX(4U)
#define UMI_STRUCT_MODEM_SIM_INFO_BND_BITMAP_SIZE	MAKE_MEMBER_SIZE(24U)
#define UMI_STRUCT_MODEM_SIM_INFO_RAT	MAKE_MEMBER_INDEX(5U)
#define UMI_STRUCT_MODEM_SIM_INFO_RAT_SIZE	MAKE_MEMBER_SIZE(1U)
#define UMI_STRUCT_MODEM_SIM_INFO_STATUS	MAKE_MEMBER_INDEX(6U)
#define UMI_STRUCT_MODEM_SIM_INFO_STATUS_SIZE	MAKE_MEMBER_SIZE(1U)
#define UMI_STRUCT_MODEM_SIM_INFO__MEMBER_COUNT	MAKE_MEMBER_INDEX(7U)
#define UMI_STRUCT_MODEM_SIM_INFO_FSN	MAKE_MEMBER_INDEX(8U)
#define UMI_STRUCT_MODEM_SIM_INFO_FSN_SIZE MAKE_MEMBER_SIZE(1U)


/* Declaration of the structure umi_modem_cfg_native_object_t. */
typedef struct
{
    egm_uint8_t access_point_name[64];
    egm_uint8_t remote_address[128];
    egm_uint16_t remote_port;
    egm_uint8_t cnx_type[4];
    egm_uint8_t bnd_bitmap0[24];
    egm_uint8_t bnd_bitmap1[24];
    egm_uint16_t wait_for_response_timeout;
    egm_uint16_t wait_for_registration_timeout;
    egm_uint16_t communication_session_timeout;
    egm_uint8_t rat1;
    egm_uint8_t rat2;
    egm_uint8_t rat3;
    egm_uint8_t padding;
} umi_modem_cfg_native_object_t;
#define UMI_STRUCT_MODEM_CFG_ACCESS_POINT_NAME	MAKE_MEMBER_INDEX(0U)
#define UMI_STRUCT_MODEM_CFG_ACCESS_POINT_NAME_SIZE	MAKE_MEMBER_SIZE(64U)
#define UMI_STRUCT_MODEM_CFG_REMOTE_ADDRESS	MAKE_MEMBER_INDEX(1U)
#define UMI_STRUCT_MODEM_CFG_REMOTE_ADDRESS_SIZE	MAKE_MEMBER_SIZE(128U)
#define UMI_STRUCT_MODEM_CFG_REMOTE_PORT	MAKE_MEMBER_INDEX(2U)
#define UMI_STRUCT_MODEM_CFG_REMOTE_PORT_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_CFG_CNX_TYPE	MAKE_MEMBER_INDEX(3U)
#define UMI_STRUCT_MODEM_CFG_CNX_TYPE_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_CFG_BND_BITMAP0	MAKE_MEMBER_INDEX(4U)
#define UMI_STRUCT_MODEM_CFG_BND_BITMAP0_SIZE	MAKE_MEMBER_SIZE(24U)
#define UMI_STRUCT_MODEM_CFG_BND_BITMAP1	MAKE_MEMBER_INDEX(5U)
#define UMI_STRUCT_MODEM_CFG_BND_BITMAP1_SIZE	MAKE_MEMBER_SIZE(24U)
#define UMI_STRUCT_MODEM_CFG_WAIT_FOR_RESPONSE_TIMEOUT	MAKE_MEMBER_INDEX(6U)
#define UMI_STRUCT_MODEM_CFG_WAIT_FOR_RESPONSE_TIMEOUT_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_CFG_WAIT_FOR_REGISTRATION_TIMEOUT	MAKE_MEMBER_INDEX(7U)
#define UMI_STRUCT_MODEM_CFG_WAIT_FOR_REGISTRATION_TIMEOUT_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_CFG_COMMUNICATION_SESSION_TIMEOUT	MAKE_MEMBER_INDEX(8U)
#define UMI_STRUCT_MODEM_CFG_COMMUNICATION_SESSION_TIMEOUT_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_CFG_RAT1	MAKE_MEMBER_INDEX(9U)
#define UMI_STRUCT_MODEM_CFG_RAT1_SIZE	MAKE_MEMBER_SIZE(1U)
#define UMI_STRUCT_MODEM_CFG_RAT2	MAKE_MEMBER_INDEX(10U)
#define UMI_STRUCT_MODEM_CFG_RAT2_SIZE	MAKE_MEMBER_SIZE(1U)
#define UMI_STRUCT_MODEM_CFG_RAT3	MAKE_MEMBER_INDEX(11U)
#define UMI_STRUCT_MODEM_CFG_RAT3_SIZE	MAKE_MEMBER_SIZE(1U)
#define UMI_STRUCT_MODEM_CFG_PADDING	MAKE_MEMBER_INDEX(12U)
#define UMI_STRUCT_MODEM_CFG_PADDING_SIZE	MAKE_MEMBER_SIZE(1U)
#define UMI_STRUCT_MODEM_CFG__MEMBER_COUNT	MAKE_MEMBER_INDEX(13U)


/* Declaration of the structure umi_modem_stats_native_object_t. */
typedef struct
{
    egm_int16_t current_state;
    egm_int16_t current_action;
    egm_int16_t last_action;
    egm_int16_t last_error;
    egm_int16_t test_case;
} umi_modem_stats_native_object_t;
#define UMI_STRUCT_MODEM_STATS_CURRENT_STATE	MAKE_MEMBER_INDEX(0U)
#define UMI_STRUCT_MODEM_STATS_CURRENT_STATE_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_STATS_CURRENT_ACTION	MAKE_MEMBER_INDEX(1U)
#define UMI_STRUCT_MODEM_STATS_CURRENT_ACTION_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_STATS_LAST_ACTION	MAKE_MEMBER_INDEX(2U)
#define UMI_STRUCT_MODEM_STATS_LAST_ACTION_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_STATS_LAST_ERROR	MAKE_MEMBER_INDEX(3U)
#define UMI_STRUCT_MODEM_STATS_LAST_ERROR_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_STATS_TEST_CASE	MAKE_MEMBER_INDEX(4U)
#define UMI_STRUCT_MODEM_STATS_TEST_CASE_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_STATS__MEMBER_COUNT	MAKE_MEMBER_INDEX(5U)


/* Declaration of the structure umi_modem_comm_stats_native_object_t. */
typedef struct
{
    egm_uint32_t timestamp;
    egm_uint8_t rsrq;
    egm_uint8_t rsrp;
    egm_uint8_t band;
    egm_uint8_t local_addr[16];
} umi_modem_comm_stats_native_object_t;
#define UMI_STRUCT_MODEM_COMM_STATS_TIMESTAMP	MAKE_MEMBER_INDEX(0U)
#define UMI_STRUCT_MODEM_COMM_STATS_TIMESTAMP_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_COMM_STATS_RSRQ	MAKE_MEMBER_INDEX(1U)
#define UMI_STRUCT_MODEM_COMM_STATS_RSRQ_SIZE	MAKE_MEMBER_SIZE(1U)
#define UMI_STRUCT_MODEM_COMM_STATS_RSRP	MAKE_MEMBER_INDEX(2U)
#define UMI_STRUCT_MODEM_COMM_STATS_RSRP_SIZE	MAKE_MEMBER_SIZE(1U)
#define UMI_STRUCT_MODEM_COMM_STATS_BAND	MAKE_MEMBER_INDEX(3U)
#define UMI_STRUCT_MODEM_COMM_STATS_BAND_SIZE	MAKE_MEMBER_SIZE(1U)
#define UMI_STRUCT_MODEM_COMM_STATS_LOCAL_ADDR	MAKE_MEMBER_INDEX(4U)
#define UMI_STRUCT_MODEM_COMM_STATS_LOCAL_ADDR_SIZE	MAKE_MEMBER_SIZE(16U)
#define UMI_STRUCT_MODEM_COMM_STATS__MEMBER_COUNT	MAKE_MEMBER_INDEX(5U)


/* Declaration of the structure umi_modem_statistics_native_object_t. */
typedef struct
{
    egm_uint32_t UartTxBytes;
    egm_uint32_t UartRxBytes;
    egm_uint32_t AtTxCmd;
    egm_uint32_t AtRxCmd;
    egm_uint32_t UartTxFrames;
    egm_uint32_t UartRxFrames;
    egm_uint32_t UDPTxBytes;
    egm_uint32_t UDPRxBytes;
    egm_uint32_t UDPTxFrames;
    egm_uint32_t UDPRxFrames;
    egm_uint32_t TCPTxBytes;
    egm_uint32_t TCPRxBytes;
    egm_uint32_t TCPTxFrames;
    egm_uint32_t TCPRxFrames;
} umi_modem_statistics_native_object_t;

#define UMI_STRUCT_MODEM_STATISTICS_UARTTXBYTES	MAKE_MEMBER_INDEX(0U)
#define UMI_STRUCT_MODEM_STATISTICS_UARTTXBYTES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_UARTRXBYTES	MAKE_MEMBER_INDEX(1U)
#define UMI_STRUCT_MODEM_STATISTICS_UARTRXBYTES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_ATTXCMD	MAKE_MEMBER_INDEX(2U)
#define UMI_STRUCT_MODEM_STATISTICS_ATTXCMD_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_ATRXCMD	MAKE_MEMBER_INDEX(3U)
#define UMI_STRUCT_MODEM_STATISTICS_ATRXCMD_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_UARTTXFRAMES	MAKE_MEMBER_INDEX(4U)
#define UMI_STRUCT_MODEM_STATISTICS_UARTTXFRAMES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_UARTRXFRAMES	MAKE_MEMBER_INDEX(5U)
#define UMI_STRUCT_MODEM_STATISTICS_UARTRXFRAMES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_UDPTXBYTES	MAKE_MEMBER_INDEX(6U)
#define UMI_STRUCT_MODEM_STATISTICS_UDPTXBYTES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_UDPRXBYTES	MAKE_MEMBER_INDEX(7U)
#define UMI_STRUCT_MODEM_STATISTICS_UDPRXBYTES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_UDPTXFRAMES	MAKE_MEMBER_INDEX(8U)
#define UMI_STRUCT_MODEM_STATISTICS_UDPTXFRAMES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_UDPRXFRAMES	MAKE_MEMBER_INDEX(9U)
#define UMI_STRUCT_MODEM_STATISTICS_UDPRXFRAMES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_TCPTXBYTES	MAKE_MEMBER_INDEX(10U)
#define UMI_STRUCT_MODEM_STATISTICS_TCPTXBYTES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_TCPRXBYTES	MAKE_MEMBER_INDEX(11U)
#define UMI_STRUCT_MODEM_STATISTICS_TCPRXBYTES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_TCPTXFRAMES	MAKE_MEMBER_INDEX(12U)
#define UMI_STRUCT_MODEM_STATISTICS_TCPTXFRAMES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS_TCPRXFRAMES	MAKE_MEMBER_INDEX(13U)
#define UMI_STRUCT_MODEM_STATISTICS_TCPRXFRAMES_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_STATISTICS__MEMBER_COUNT	MAKE_MEMBER_INDEX(14U)


/* Declaration of the structure umi_modem_event_fifo_native_object_t. */
typedef struct
{
    egm_uint32_t datetime;
    egm_uint16_t state;
    egm_uint16_t error;
    egm_uint16_t action;
    egm_uint16_t data;
} umi_modem_event_fifo_native_object_t;
#define UMI_STRUCT_MODEM_EVENT_FIFO_DATETIME	MAKE_MEMBER_INDEX(0U)
#define UMI_STRUCT_MODEM_EVENT_FIFO_DATETIME_SIZE	MAKE_MEMBER_SIZE(4U)
#define UMI_STRUCT_MODEM_EVENT_FIFO_STATE	MAKE_MEMBER_INDEX(1U)
#define UMI_STRUCT_MODEM_EVENT_FIFO_STATE_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_EVENT_FIFO_ERROR	MAKE_MEMBER_INDEX(2U)
#define UMI_STRUCT_MODEM_EVENT_FIFO_ERROR_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_EVENT_FIFO_ACTION	MAKE_MEMBER_INDEX(3U)
#define UMI_STRUCT_MODEM_EVENT_FIFO_ACTION_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_EVENT_FIFO_DATA	MAKE_MEMBER_INDEX(4U)
#define UMI_STRUCT_MODEM_EVENT_FIFO_DATA_SIZE	MAKE_MEMBER_SIZE(2U)
#define UMI_STRUCT_MODEM_EVENT_FIFO__MEMBER_COUNT	MAKE_MEMBER_INDEX(5U)

